apps/funcionarios/urls.py
from django.contrib import admin
from django.urls import path
from .views import FuncionariosList, FuncionarioEdit, FuncionarioDelete, \
    FuncionarioCreate, relatorio_funcionarios, Pdf, Pdf_debug

urlpatterns = [
    path('', FuncionariosList.as_view(), name='list_funcionarios'),
    path('novo/', FuncionarioCreate.as_view(), name='create_funcionario'),
    path('edit/<int:pk>/', FuncionarioEdit.as_view(), name='update_funcionarios'),
    path('delete/<int:pk>/', FuncionarioDelete.as_view(), name='delete_funcionario'),
    path('relatorio_funcionarios', relatorio_funcionarios, name='relatorio_funcionarios'),
    path('relatorio_funcionarios_html', Pdf.as_view(), name='relatorio_funcionarios_html'),
    path('relatorio_funcionarios_html_debug', Pdf_debug.as_view(), name='relatorio_funcionarios_html_debug'),
    ]

gestao_rh/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from apps.core.views import UserViewSet
from apps.funcionarios.api.views import FuncionarioViewSet
from apps.registro_hora_extra.api.views import RegistroHoraExtraViewSet

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'api/funcionarios', FuncionarioViewSet)
router.register(r'api/horas', RegistroHoraExtraViewSet)

urlpatterns = [
    path('', include('apps.core.urls')),
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('empresas/', include('apps.empresas.urls')),
    path('departamentos/', include('apps.departamentos.urls')),
    path('documentos/', include('apps.documentos.urls')),
    path('horas-extras/', include('apps.registro_hora_extra.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

    # Wire up our API using automatic URL routing.
    # Additionally, we include login URLs for the browsable API.
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/documentos/models.py
from django.db import models
from django.urls import reverse

from apps.funcionarios.models import Funcionario


class Documento(models.Model):
    descricao = models.CharField(max_length=100)
    pertence = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    arquivo = models.FileField(upload_to='documentos')

    def get_absolute_url(self):
        return reverse('update_funcionarios', args=[self.pertence.id])

    def __str__(self):
        return self.descricao

apps/funcionarios/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse

from apps.departamentos.models import Departamento
from apps.empresas.models import Empresa

class Funcionario(models.Model):
    nome = models.CharField(max_length=100)
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    departamentos = models.ManyToManyField(Departamento)
    empresa = models.ForeignKey(Empresa, on_delete=models.PROTECT, null=True, blank=True)
    #imagem = models.ImageField()

    def get_absolute_url(self):
        return reverse('list_funcionarios')

    @property
    def total_horas_extra(self):
        return self.registrohoraextra_set.filter(utilizada=False).aggregate(Sum('horas'))['horas__sum'] or 0

    def __str__(self):
        return self.nome

apps/registro_hora_extra/models.py
from django.db import models
from django.urls import reverse

from apps.funcionarios.models import Funcionario


class RegistroHoraExtra(models.Model):
    motivo = models.CharField(max_length=100)
    funcionario = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    horas = models.DecimalField(max_digits=5, decimal_places=2)
    utilizada = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('update_funcionarios', args=[self.funcionario.id])


    def __str__(self):
        return self.motivo

apps/funcionarios/api/views.py
from rest_framework import viewsets
from apps.funcionarios.api.serializers import FuncionarioSerializer
from apps.funcionarios.models import Funcionario
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication


# ViewSets define the view behavior.
class FuncionarioViewSet(viewsets.ModelViewSet):
    queryset = Funcionario.objects.all()
    serializer_class = FuncionarioSerializer
    autentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)

apps/funcionarios/views.py
from django.contrib.auth.models import User
from django.http import HttpResponse, FileResponse
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, UpdateView, DeleteView, CreateView, View, TemplateView
from .models import Funcionario
import io
from reportlab.pdfgen import canvas
from django.template.loader import get_template
from xhtml2pdf import pisa


class FuncionariosList(ListView):
    model = Funcionario

    def get_queryset(self):
        empresa_logada = self.request.user.funcionario.empresa
        return Funcionario.objects.filter(empresa=empresa_logada)


class FuncionarioEdit(UpdateView):
    model = Funcionario
    fields = ['nome', 'departamentos']


class FuncionarioDelete(DeleteView):
    model = Funcionario
    success_url = reverse_lazy('list_funcionarios')


class FuncionarioCreate(CreateView):
    model = Funcionario
    fields = ['nome', 'departamentos']

    def form_valid(self, form):
        funcionario = form.save(commit=False)
        username = funcionario.nome.split(' ')[0] + funcionario.nome.split(' ')[1]
        funcionario.empresa = self.request.user.funcionario.empresa
        funcionario.user = User.objects.create(username=username)
        funcionario.save()
        return super(FuncionarioCreate, self).form_valid(form)


def relatorio_funcionarios(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="mypdf.pdf"'
    
    buffer = io.BytesIO()
    p = canvas.Canvas(buffer)

    p.drawString(10, 810, 'Relatório de funcionarios')

    funcionarios = Funcionario.objects.filter(empresa=request.user.funcionario.empresa)

    str_ = 'Nome: %s | Hora Extra %.2f'

    y = 790
    for funcionario in funcionarios:
        p.drawString(10, y, str_ % (funcionario.nome, funcionario.total_horas_extra))
        y -= 40

    # Close the PDF object cleanly, and we're done.
    p.showPage()
    p.save()

    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)

    # FileResponse sets the Content-Disposition header so that browsers
    # present the option to save the file.
    #buffer.seek(0)
    return response

class Render:
  @staticmethod
  def render(path:str, params: dict, filename:str):
    template = get_template(path)
    html = template.render(params)
    response = io.BytesIO()
    pdf = pisa.pisaDocument(
      io.BytesIO(html.encode("UTF-8")), response)
    if not pdf.err:
      response = HttpResponse(
        response.getvalue(), content_type='application/pdf')
      response['Content-Disposition'] = 'attachment; filename=%s.pdf' % filename
      return response
    else:
      return HttpResponse("Error Rendering PDF", status=400)

class Pdf(View):

  def get(self, request):
    params = {
      'today': 'Variavel today',
      'sales': 'Variavel sales',
      'request': request,
    }
    return Render.render('funcionarios/relatorio.html', params, 'myfile')

class Pdf_debug(TemplateView):
    params = {
        'today': 'Variavel today',
        'sales': 'Variavel sales',

    }
    template_name = 'funcionarios/relatorio.html';

    def get_context_data(self, **kwargs):
        params = {
            'today': 'Variavel today',
            'sales': 'Variavel sales',

        }
        return params

apps/funcionarios/templates/funcionarios/funcionario_confirm_delete.html
{% extends 'base.html' %}


{% block main %}
    Edit
    <form method="post">
        {% csrf_token %}
        <h1>tem certeza que deseja excluir {{ obj }}</h1>
        {{ form }}
        <button type="submit">Confirmar</button>
    </form>
{% endblock %}

apps/funcionarios/templates/funcionarios/funcionario_form.html
{% extends 'base.html' %}

{% load bootstrap %}

{% block main %}

    <form method="post" >
        {% csrf_token %}
        {{ form|bootstrap }}
        <button type="submit">Salvar</button>
    </form>


    <br>
    <h3>Documentos</h3>
    <ul>
    {% for documento in object.documento_set.all %}

        <li>
            <a href="{{documento.arquivo.url }}">{{documento.descricao}}</a>
        </li>
    {% endfor %}
    </ul>
    {% if object %}
        <a href="{% url 'create_documento' object.id %}" class="btn btn-success">Adicionar documento</a>
    {% endif %}

    <br>
    <h3>Banco de horas</h3>
    <ul>
    {% for registro_hora in object.registrohoraextra_set.all %}

        <li>
           <a href="{% url 'update_hora_extra' registro_hora.id %}">
               {{registro_hora.motivo}} | {{registro_hora.horas}}
           </a>
        </li>
    {% endfor %}
    </ul>
    <h3> total de horas extra {{ object.total_horas_extra }}</h3>

{% endblock %}

apps/funcionarios/templates/funcionarios/funcionario_list.html
{% extends 'base.html' %}


{% block main %}
    lista de funcionários:<br>
    {% for funcionario in object_list %}
        <a href="{% url 'update_funcionarios' funcionario.id %}">
            {{ funcionario }}
        </a> |
        <a href="{% url 'delete_funcionario' funcionario.id %}">Deletar</a><br>
    {% endfor %}
    <a href="{% url 'create_funcionario' %}" class="btn btn-info">novo</a><br/>
    <a href="{% url 'relatorio_funcionarios' %}">Relatório funcionarios</a> |
    <a href="{% url 'relatorio_funcionarios_html' %}">Relatório funcionarios Html</a> |
    <a href="{% url 'relatorio_funcionarios_html_debug' %}">Relatório funcionarios Html Debug</a>

{% endblock %}

apps/funcionarios/templates/funcionarios/relatorio.html
{% extends 'base.html' %}

{% block main %}
    <h1 style="font-size:40px; color:red;">Relatório de funcionarios</h1>
    <h2>{{ sales }}</h2>
{% endblock %}